CREATE IF NOT EXISTS DATABASE xxxxxxxxxx;

CREATE USER IF NOT EXISTS foobar WITH ENCRYPTED PASSWORD 'xxxxxxxx';

GRANT ALL PRIVILEGES ON DATABASE xxxxxxxxxx TO foobar;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    is_superuser BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
