CREATE IF NOT EXISTS DATABASE db_course;

CREATE USER IF NOT EXISTS foobar WITH ENCRYPTED PASSWORD '1234';

GRANT ALL PRIVILEGES ON DATABASE db_course TO foobar;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    is_superuser BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
